@baseUrl = http://localhost:8100
@apiVersion = 1.0
@id = 1A40D49E-75CE-44F5-9600-E7FE2582700C
@clusterId = 99AD9A58-5155-4327-8B48-88FA21E7D5F8

### Get all routes
GET {{baseUrl}}/api/routes?api-version={{apiVersion}}
Accept: application/json

### Create the route
POST {{baseUrl}}/api/routes?api-version={{apiVersion}}
Content-Type: application/json

{
    "name": "example",
    "clusterId": "{{clusterId}}",
    "order": 10,
    "authorizationPolicy": null,
    "rateLimiterPolicy": null ,
    "corsPolicy": null,
    "timeoutPolicy": null,
    "timeout": "00:00:01",
    "maxRequestBodySize": 1000,
    "match": {
        "path": "{**catch-all}",
        "hosts": [
            "www.example.com"
        ],
        "methods": [
            "GET",
            "POST",
            "DELETE",
            "PUT"
        ],
        "queryParameters": [
            {
                "name": "queryparam1",
                "values": [
                    "value1"
                ],
                "mode": 1
            }
        ],
        "headers": [
            {
                "name": "header3",
                "mode": 1
            }
        ]
    },
    "transforms": [
        {
            "PathPrefix": "/apis"
        },
        {
            "RequestHeader": "header1",
            "Append": "bar"
        },
        {
            "ResponseHeader": "header2",
            "Append": "bar",
            "When": "Always"
        },
        {
            "ClientCert": "X-Client-Cert"
        },
        {
            "RequestHeadersCopy": "true"
        },
        {
            "RequestHeaderOriginalHost": "true"
        },
        {
            "X-Forwarded": "Append",
            "HeaderPrefix": "X-Forwarded-"
        }
    ]
}

### Update the route
PUT {{baseUrl}}/api/routes/{{id}}?api-version={{apiVersion}}
Content-Type: application/json

{
  "name": "example-updater",
  "clusterId": "{{clusterId}}",
   "order": 10,
   "authorizationPolicy": "auth",
   "rateLimiterPolicy": "rate-limier",
   "corsPolicy": "cors",
   "timeoutPolicy": "timeout",
   "timeout": "00:00:01",
   "maxRequestBodySize": -1,
   "match": {
      "path": "{**catch-all}",
      "hosts": ["www.example.com"],
      "methods": ["GET","POST","DELETE","PUT"],
      "queryParameters": [
        {
          "name": "queryparam1",
          "values": [ "value1" ],
          "mode": 1
        }
      ],
       "headers": [
        {
          "name": "header3",
          "mode": 1
        }
      ]
   }
}

### Delete the route
DELETE {{baseUrl}}/api/routes/{{id}}?api-version={{apiVersion}}